SERVER       = 'irc.freenode.net'
PORT         = 6667
CHANNEL      = '#munin_test_chan'
NICKNAME     = 'i_am_a_bot'
REALNAME     = 'gérard'
CHECK_TIME   = 5
PASSWORD     = ''
SUDOERS      = {'master', 'gérard'}
EXPRESSIONS  = {'my friend', 'little man'}
EXPRESSIVITY = 0.1
